name: oauth2

options:
  bundleIdPrefix: dev.jano.oauth2
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.0

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

packages:
    
  APIClient:
    url: git@github.com:janodevorg/APIClient.git
    from: 1.0.0
    
  AutoLayout:
    url: git@github.com:janodevorg/AutoLayout.git
    from: 1.0.0

  CodableHelpers:
    url: git@github.com:janodevorg/CodableHelpers.git
    from: 1.0.0

  Dependency:
    url: git@github.com:janodevorg/Dependency.git
    from: 1.0.0

  Keychain:
    url: git@github.com:janodevorg/Keychain.git
    from: 1.0.0
    
  Report:
    url: git@github.com:janodevorg/Report.git
    from: 1.0.0

targets:

  OAuth2:
    dependencies:
      - package: APIClient
      - package: AutoLayout
      - package: CodableHelpers
      - package: Dependency
      - package: Keychain
      - package: Report
    type: framework
    platform: iOS
    scheme:
      testTargets:
         - OAuth2Tests
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 15.0
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.oauth2
       PRODUCT_NAME: OAuth2
    sources: 
       - sources/main
    type: framework

  OAuth2Tests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.oauth2.tests
      TEST_HOST:
    sources:
      - sources/tests
    dependencies:
      - target: OAuth2
